version: '3'

services:
  node:
    build:
      context: ./
    container_name: node
    networks:
      - nodenet
    tty: true
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - nodenet

  mysql: 
    container_name: mysql
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "node_app"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_USER: "root"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge